# Deployment definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-alpine-deployment
  labels:
    app: node-alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-alpine
  template:
    metadata:
      labels:
        app: node-alpine
    spec:
      containers:
      - name: node-alpine
        image: node-alpine:2.0
        workingDir: /home/node/app
        env:
        - name: NODE_ENV
          value: development
        ports:
        - containerPort: 30000
        command: ["npm", "start"]

---

# Service definition
apiVersion: v1
kind: Service
metadata:
  name: node-alpine-service-03
spec:
  selector:
    app: node-alpine
  ports:
  - protocol: TCP
    port: 30000
    targetPort: 30000
  type: NodePort