# Deployment definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-alpine-deployment
  labels:
    app: node-alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-alpine
  template:
    metadata:
      labels:
        app: node-alpine
    spec:
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
          type: File
      - name: challenges
        hostPath:
          path: /home/node/app/challenges.json
          type: FileOrCreate
      - name: public-keys
        hostPath:
          path: /home/node/app/public_keys.json
          type: FileOrCreate
      - name: shared-secrets
        hostPath:
          path: /home/node/app/shared_secrets.json
          type: FileOrCreate
      - name: idcs
        hostPath:
          path: /home/node/app/idcs.json
          type: FileOrCreate
      containers:
      - name: node-alpine
        image: node-alpine:2.0
        workingDir: /home/node/app
        resources:
          requests:
            memory: "1024Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        - name: NODE_ENV
          value: development
        - name: TZ
          value: America/Mexico_City
        ports:
        - containerPort: 30000
        command: ["npm", "start"]
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true

---

# Service definition
apiVersion: v1
kind: Service
metadata:
  name: node-alpine-service-02
spec:
  selector:
    app: node-alpine
  ports:
  - protocol: TCP
    port: 30000
    targetPort: 30000
  type: NodePort